# Generated by Django 3.1.2 on 2021-08-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210822_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='client_posts',
            new_name='client_allposts',
        ),
    ]
