# Generated by Django 3.1.2 on 2021-08-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210822_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='person',
            new_name='person_all',
        ),
    ]
