# Generated by Django 3.1.2 on 2021-08-22 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20210822_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='client_allposts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_posts', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='person_all',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
