# Generated by Django 3.1.2 on 2021-08-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210822_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='send_user',
            new_name='send',
        ),
    ]
